[general]
import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]

[font]
size = 24.0

[font.bold]
family = "Terminus"
style = "Bold"

[font.bold_italic]
family = "Terminus"
style = "Bold Italic"

[font.italic]
family = "Terminus"
style = "Italic"

[font.normal]
family = "Terminus"
style = "Regular"
