[general]
import = [
    "~/.config/alacritty/themes/themes/enfocado_dark.toml"
]

[font]
size = 16.0

[font.bold]
family = "Terminus"
style = "Bold"

[font.bold_italic]
family = "Terminus"
style = "Bold Italic"

[font.italic]
family = "Terminus"
style = "Italic"

[font.normal]
family = "Terminus"
style = "Regular"

[window.padding]
x = 16
y = 16

